#!/bin/csh
setenv PETOOLS_ROOT            /opt64
setenv PETOOLS_PREFIX          /opt64
setenv SPD_CLIENT_PREFIX       /opt64
setenv SPD_CLIENT_LIB          /opt64/lib
setenv NERS_LIB                /opt64/lib
setenv NERS_INC                /opt64/include
setenv VTD_LIB                 /opt64/lib
setenv VTD_INC                 /opt64/include
setenv TLE_LIB                 /opt64/lib
setenv TLE_INC                 /opt64/include
setenv GVH_LIB                 /opt64/lib
setenv GVH_INC                 /opt64/include
setenv VEX_LIB                 /opt64/lib
setenv VEX_INC                 /opt64/include
setenv SOLVE_LIB_GVH      "-L/opt64/lib -lgvh -lvcat"
setenv SOLVE_LIB_VTD      "-L/opt64/lib -lvtd -L/opt64/lib -lspc -L/opt64/lib -L/opt64/lib -ltle -lners"
setenv SOLVE_LIB_PETOOLS  "-L/opt64/lib -lpetools -L /opt64/lib -lreadline -L /opt64/lib64 -lncurses"
setenv SOLVE_LIB_PGPLOT   "-L/opt64/lib -lpgplot"
setenv SOLVE_LIB_X11      "/usr/lib64/libX11.so"
setenv SOLVE_LIB_XT       " "
setenv SOLVE_LIB_X11      "/usr/lib64/libX11.so"
setenv SOLVE_LIB_XHP11    " "
setenv SOLVE_EXTRA_LIB    "-lpthread -lrt -L /opt64/lib -lz -L /opt64/lib -lpng"
setenv SOLVE_LIB_VEC      " "
setenv SOLVE_LIB_BLAS     "-L/opt64/lib -lopenblas"
setenv MK5_C              "/usr/bin/gcc  -m64 -mtune=native -fopenmp -fpermissive -fPIC -D LINUX -D LITTLE_ENDIAN -D FORTRAN_TRUE=1 -D FORTRAN_FALSE=0 -D _FILE_OFFSET_BITS=64 -D _LARGEFILE_SOURCE -I ./ -I ../include -I /usr/include -I /usr/local/include -fno-diagnostics-color --std=gnu11 -I /opt64/include"
setenv MK5_X11_INCLUDE    "/usr/include"
setenv MK5_F95            "/usr/bin/gfortran -m64 -ffree-form -ffree-line-length-none -fmax-errors=16 -fno-underscoring -fdollar-ok -fopenmp -x f95-cpp-input -finit-integer=-2147483647 -finit-logical=false -finit-real=nan -finit-character=0 -fbacktrace -ftrapv -fPIC -ffpe-trap=overflow,invalid,zero -fexceptions -fPIC -D LINUX -D GNU -D LITTLE_ENDIAN -D ADDRESS__TYPE=INTEGER\(8\) -D ADR_64BIT -D BLAS=openblas -fno-diagnostics-color -fallow-argument-mismatch -Wno-align-commons -J /opt64/module -I ./ -I /f1/progs/psolve_20260812/include -I /opt64/include -Wall -Wno-align-commons -Wno-character-truncation -Wno-conversion -Wno-implicit-interface -Wno-implicit-procedure -Wno-integer-division -Wno-tabs -Wno-unused -fcheck=all -O2 -mavx2"
setenv MK5_F95_OPT        "/usr/bin/gfortran -m64 -ffree-form -ffree-line-length-none -fmax-errors=16 -fno-underscoring -fdollar-ok -fopenmp -x f95-cpp-input -finit-integer=-2147483647 -finit-logical=false -finit-real=nan -finit-character=0 -fbacktrace -fPIC -mtune=native -D LINUX -D GNU -D LITTLE_ENDIAN -D ADDRESS__TYPE=INTEGER\(8\) -D ADR_64BIT -D BLAS=openblas -fno-diagnostics-color -fallow-argument-mismatch -Wno-align-commons -mavx2 -J /opt64/module -I ./ -I /f1/progs/psolve_20260812/include -I /opt64/include -Wall -Wno-align-commons -Wno-character-truncation -Wno-conversion -Wno-implicit-interface -Wno-implicit-procedure -Wno-integer-division -Wno-tabs -Wno-unused -mavx -O3"
setenv MK5_F95_OPTEST     "/usr/bin/gfortran -m64 -ffree-form -ffree-line-length-none -fmax-errors=16 -fno-underscoring -fdollar-ok -fopenmp -x f95-cpp-input -finit-integer=-2147483647 -finit-logical=false -finit-real=nan -finit-character=0 -fbacktrace -fPIC -mtune=native -D LINUX -D GNU -D LITTLE_ENDIAN -D ADDRESS__TYPE=INTEGER\(8\) -D ADR_64BIT -D BLAS=openblas -fno-diagnostics-color -fallow-argument-mismatch -Wno-align-commons -mavx2 -J /opt64/module -I ./ -I /f1/progs/psolve_20260812/include -I /opt64/include -Wall -Wno-align-commons -Wno-character-truncation -Wno-conversion -Wno-implicit-interface -Wno-implicit-procedure -Wno-integer-division -Wno-tabs -Wno-unused -mavx -Ofast -ftree-vectorize"
setenv MK5_F95_NOOPT      "/usr/bin/gfortran -m64 -ffree-form -ffree-line-length-none -fmax-errors=16 -fno-underscoring -fdollar-ok -fopenmp -x f95-cpp-input -finit-integer=-2147483647 -finit-logical=false -finit-real=nan -finit-character=0 -fbacktrace -ftrapv -fPIC -ffpe-trap=overflow,invalid,zero -fexceptions -fPIC -D LINUX -D GNU -D LITTLE_ENDIAN -D ADDRESS__TYPE=INTEGER\(8\) -D ADR_64BIT -D BLAS=openblas -fno-diagnostics-color -fallow-argument-mismatch -Wno-align-commons -J /opt64/module -I ./ -I /f1/progs/psolve_20260812/include -I /opt64/include -Wall -Wno-align-commons -Wno-character-truncation -Wno-conversion -Wno-implicit-interface -Wno-implicit-procedure -Wno-integer-division -Wno-tabs -Wno-unused -fcheck=all -O0 -g"
setenv MK5_LINK           "/usr/bin/gfortran  -m64 -fopenmp -Wl,--gc-sections,--no-warn-search-mismatch"
setenv MK5_C_LINK         "/usr/bin/gfortran  -m64 -fopenmp -Wl,--gc-sections,--no-warn-search-mismatch"
setenv SOLVE_ROOT              /f1/progs/psolve_20260812
setenv SOLVE_PREFIX            /opt64
setenv SOLVE_BIN               /opt64/bin
setenv SOLVE_INC               /opt64/include
setenv SOLVE_LIB               /opt64/lib
setenv SOLVE_SCRATCH_DATA      /scr/psolve
setenv SOLVE_SAVE_DATA         /opt64/share/psolve
setenv SOLVE_GVF_DATA          /l2/gvf
setenv SOLVE_SCRATCH_PIMA      /scr/pima
setenv SOLVE_CENTER_ABR        NAS
setenv SOLVE_CENTER_NAM   "NASA GSFC"
setenv SOLVE_PS_VIEWER         /usr/bin/display
setenv SOLVE_GIF_VIEWER        /usr/bin/display
setenv SOLVE_CFITSIO_LIB  "-L /opt64/lib -lcfitsio"
setenv SOLVE_FITSLIB_LIB  "-L /opt64/lib -lfitslib"
setenv FOURPACK_PREFIX    "/opt64"
setenv SOLVE_FFTW_DIR     "/opt64"
setenv SOLVE_FFTW_INC     "-I/opt64/include"
setenv SOLVE_FFTW_LIB     "-L/opt64/lib -lfftw3 -lfftw3_omp -lfftw3f -lfftw3f_omp"
setenv SOLVE_OPT_NOSTRUC  ""
setenv SOLVE_OS           Linux
setenv SOLVE_VERSION      20260812
umask 0022
