"""
Global variables for PIMA script for host %%host%%
Generated on %%date%%
"""
pf_dir               = "%%pf_dir%%"
pima_path            = "%%pima_path%%"
doc_path             = "%%doc_path%%"
pima_dynamic_exec    = "%%pima_dynamic_exec%%"
pima_static_exec     = "%%pima_static_exec%%"
fitsh                = "%%fitsh%%"
fits_to_map_exec     = "%%fits_to_map_exec%%"
fits_to_radplot_exec = "%%fits_to_radplot_exec%%"
fits_to_cfd_exec     = "%%fits_to_cfd_exec%%"
log_to_antab_exec    = "%%log_to_antab_exec%%"
gvf_promote_exec     = "%%gvf_promote_exec%%"
gvf_db_exec          = "%%gvf_db_exec%%"
samb_exec            = "%%samb_exec%%"
difmap_exec          = "%%difmap_exec%%"
automap_exec         = "%%automap_exec%%"
pima_share_dir       = "%%pima_share_dir%%"
pima_vtd             = "%%pima_share_dir%%/vtd_pima.cnf"
pima_psolve          = "%%pima_share_dir%%/psolve_bas.cnt"
ners_prefix          = "%%ners_prefix%%"
spc_prefix           = "%%spc_prefix%%"
vtd_prefix           = "%%vtd_prefix%%"
spd_url              = "%%spd_url%%"
