"""
Global variables for PIMA script for host astrogeo
Generated on 2026.08.18-15:12:58
"""
pf_dir               = "/vlbi"
pima_path            = "/opt64"
doc_path             = "/opt64/doc"
pima_dynamic_exec    = "/opt64/bin/pima"
pima_static_exec     = "/f1/progs/pima_20260516/bin/pima_static"
fitsh                = "/opt64/bin/fitsh"
fits_to_map_exec     = "/opt64/bin/fits_to_map"
fits_to_radplot_exec = "/opt64/bin/fits_to_radplot"
fits_to_cfd_exec     = "/opt64/bin/fits_to_cfd"
log_to_antab_exec    = "/opt64/bin/log_to_antab"
log_to_anc_exec      = "/opt64/bin/log2ant"
gvf_promote_exec     = "/opt64/bin/gvf_supr_promote"
gvf_db_exec          = "/opt64/bin/gvf_db"
samb_exec            = "/opt64/psolve/bin/samb"
difmap_exec          = "/opt64/bin/difmap"
automap_exec         = "/opt64/bin/automap.py"
pima_share_dir       = "/opt64/share/pima"
pima_vtd             = "/opt64/share/pima/vtd_pima.cnf"
pima_psolve          = "/opt64/share/pima/psolve_bas.cnt"
ners_prefix          = "/opt64"
spc_prefix           = "/opt64"
vtd_prefix           = "/opt64"
spd_url              = "https://atmospheric-propagation.smce.nasa.gov/spd/asc/geosit"
