#######################################################################
#								      #
#	Make file for building pima                                   #
#						     		      #
#  %%%  31-JAN-2011  makefile   v1.0  (c) L. Petrov  31-JAN-2011 %%%  #
#								      #
#######################################################################
.SUFFIXES:
.SUFFIXES:	.f	.c	.o	.opt_o	.a	.d
#
SHELL = /bin/csh -f -c 'umask 0022; eval "$2"'

DATE = `date '+%Y%m%d'`

