# SPD_CONFIG file.  Format of 2025.06.15
#
# Last updated on 2026.05.18_09:22:06
#
heb_dir:               /imls/heb/geosfpit
spd_conf:              /opt64/spd/share/spd_geosfpit_vlbi.cnf	
spd_dir:               /spd/asc/geosfpit
run_bspd_export:       no
bspd_export_stop_file: /imls/logs/sagitta_export.stop
bspd_dir: 	       /spd/bin/geosfpit
bspd_export_dir:       /spd/ex/spd/bin/opa_geosfpit
bspd_sandbox_dir:      /spd/ex/spd/export_sandbox/opa_geosfpit
bspd_grace_int:        50
bspd_prefix:           geosfpit_vlbi_
spd_prefix:            spd_geosfpit_
spd_ext:               .spd
pivot_name:            d
spd_path:              /opt64
spd_3d_bin:            /opt64/bin/spd_3d
spd_3d_toser:          /opt64/bin/spd_3d_toser
stop_file:             /imls/logs/astrogeo.stop
err_file:              /imls/logs/spd_geosfpit.err
suc_file:              /imls/logs/spd_geosfpit.suc
lock_file:             /imls/logs/spd_geosfpit.lock
lock_timeout:          43200
num_cpu:               8
