#######################################################################
#								      #
#	Make file for building fourpack                               #
#						     		      #
#  %%%  15-JUN-2009  makefile   v1.1  (c) L. Petrov  07-NOV-2012 %%%  #
#								      #
#######################################################################
.SUFFIXES:
.SUFFIXES:	.f	.c	.o	.opt_o	.a	.d
#
SHELL = /bin/csh -f -c 'umask 0002; eval "$2"'

DATE = `date '+%Y.%m.%d-%H:%M:%S'`

