!
! %%
!
      CHARACTER    TLE__ROOT*%ROOT_LEN%
      CHARACTER    TLE__PREFIX*%PREFIX_LEN%
      CHARACTER    TLE__VERSION*%VERSION_LEN%
      PARAMETER  ( TLE__ROOT      = "%ROOT_VAL%" )
      PARAMETER  ( TLE__PREFIX    = "%PREFIX_VAL%" )
      PARAMETER  ( TLE__VERSION   = "%VERSION_VAL%"  )
