#######################################################################
#								      #
#	Make file for building spd                                    #
#						     		      #
#  %%%  26-JUN-2008  makefile   v1.0  (c) L. Petrov  26-JUN-2008 %%%  #
#								      #
#######################################################################
.SUFFIXES:
.SUFFIXES:	.f	.c	.o	.opt_o	.a	.d
#
SHELL = /bin/csh -f -c 'umask 0002; eval "$2"'

DATE = `date '+%Y%m%d'`

