      PROGRAM    SPC_TEST_01
      CHARACTER  SPD_CLIENT_VERSION_STR*8
      CALL SPD_CLIENT_VERSION ( 'SPD_CLIENT_VERSION', SPD_CLIENT_VERSION_STR)
      WRITE ( 6, '(A)' ) SPD_CLIENT_VERSION_STR
      END  !#!  
