mkdir -p /imls/load_bds
mkdir -p /imls/load_bds/atm
mkdir -p /imls/load_bds/atm/geosfpit
mkdir -p /imls/load_bds/atm/geosit
mkdir -p /imls/load_bds/atm/merra2
mkdir -p /imls/load_bds/lws
mkdir -p /imls/load_bds/lws/geosfpit
mkdir -p /imls/load_bds/lws/geosit
mkdir -p /imls/load_bds/lws/merra2
mkdir -p /imls/load_bds/nto
mkdir -p /imls/load_bds/nto/mpiom06
mkdir -p /imls/load_bds/nto/mpiom07
mkdir -p /imls/load_d1_grid
mkdir -p /imls/load_d1_grid/atm
mkdir -p /imls/load_d1_grid/atm/geosfpit
mkdir -p /imls/load_d1_grid/atm/geosit
mkdir -p /imls/load_d1_grid/atm/merra2
mkdir -p /imls/load_d1_grid/lws
mkdir -p /imls/load_d1_grid/lws/geosfpit
mkdir -p /imls/load_d1_grid/lws/geosit
mkdir -p /imls/load_d1_grid/lws/merra2
mkdir -p /imls/load_d1_grid/nto
mkdir -p /imls/load_d1_grid/nto/mpiom06
mkdir -p /imls/load_d1_grid/nto/mpiom07
mkdir -p /imls/load_d1_har_grid
mkdir -p /imls/load_d1_har_grid/atm
mkdir -p /imls/load_d1_har_grid/atm/geosfpit
mkdir -p /imls/load_d1_har_grid/atm/geosit
mkdir -p /imls/load_d1_har_grid/atm/merra2
mkdir -p /imls/load_d1_har_grid/lws
mkdir -p /imls/load_d1_har_grid/lws/geosfpit
mkdir -p /imls/load_d1_har_grid/lws/geosit
mkdir -p /imls/load_d1_har_grid/lws/merra2
mkdir -p /imls/load_d1_har_grid/nto
mkdir -p /imls/load_d1_har_grid/nto/mpiom06
mkdir -p /imls/load_d1_har_grid/nto/mpiom07
mkdir -p /imls/load_d1_har_grid/toc
mkdir -p /imls/load_d1_har_grid/toc/equil01
mkdir -p /imls/load_d1_har_grid/toc/equil02
mkdir -p /imls/load_d1_har_grid/toc/fes2012
mkdir -p /imls/load_d1_har_grid/toc/fes2014b
mkdir -p /imls/load_d1_har_grid/toc/got410c
mkdir -p /imls/load_d1_har_grid/toc/got48
mkdir -p /imls/load_d1_har_grid/toc/lpequil
mkdir -p /imls/load_d1_har_list
mkdir -p /imls/load_d1_har_list/atm
mkdir -p /imls/load_d1_har_list/atm/geosfpit
mkdir -p /imls/load_d1_har_list/atm/geosit
mkdir -p /imls/load_d1_har_list/atm/merra2
mkdir -p /imls/load_d1_har_list/lws
mkdir -p /imls/load_d1_har_list/lws/geosfpit
mkdir -p /imls/load_d1_har_list/lws/geosit
mkdir -p /imls/load_d1_har_list/lws/merra2
mkdir -p /imls/load_d1_har_list/nto
mkdir -p /imls/load_d1_har_list/nto/mpiom06
mkdir -p /imls/load_d1_har_list/nto/mpiom07
mkdir -p /imls/load_d1_har_list/nto/omct
mkdir -p /imls/load_d1_har_list/toc
mkdir -p /imls/load_d1_har_list/toc/equil01
mkdir -p /imls/load_d1_har_list/toc/equil02
mkdir -p /imls/load_d1_har_list/toc/fes2012
mkdir -p /imls/load_d1_har_list/toc/fes2014b
mkdir -p /imls/load_d1_har_list/toc/got410c
mkdir -p /imls/load_d1_har_list/toc/got48
mkdir -p /imls/load_d1_har_list/toc/lpequil
mkdir -p /imls/load_d1_har_spl
mkdir -p /imls/load_d1_har_spl/atm
mkdir -p /imls/load_d1_har_spl/atm/geosfpit
mkdir -p /imls/load_d1_har_spl/atm/geosit
mkdir -p /imls/load_d1_har_spl/atm/merra2
mkdir -p /imls/load_d1_har_spl/lws
mkdir -p /imls/load_d1_har_spl/lws/geosfpit
mkdir -p /imls/load_d1_har_spl/lws/geosit
mkdir -p /imls/load_d1_har_spl/lws/merra2
mkdir -p /imls/load_d1_har_spl/nto
mkdir -p /imls/load_d1_har_spl/nto/mpiom06
mkdir -p /imls/load_d1_har_spl/nto/mpiom07
mkdir -p /imls/load_d1_har_spl/toc
mkdir -p /imls/load_d1_har_spl/toc/equil01
mkdir -p /imls/load_d1_har_spl/toc/equil02
mkdir -p /imls/load_d1_har_spl/toc/fes2012
mkdir -p /imls/load_d1_har_spl/toc/fes2014b
mkdir -p /imls/load_d1_har_spl/toc/got410c
mkdir -p /imls/load_d1_har_spl/toc/got48
mkdir -p /imls/load_d1_har_spl/toc/lpequil
mkdir -p /imls/load_d1_int
mkdir -p /imls/load_d1_int/atm
mkdir -p /imls/load_d1_int/atm/geosfpit
mkdir -p /imls/load_d1_int/atm/geosit
mkdir -p /imls/load_d1_int/atm/merra2
mkdir -p /imls/load_d1_int/lws
mkdir -p /imls/load_d1_int/lws/geosfpit
mkdir -p /imls/load_d1_int/lws/geosit
mkdir -p /imls/load_d1_int/lws/merra2
mkdir -p /imls/load_d1_int/nto
mkdir -p /imls/load_d1_int/nto/mpiom06
mkdir -p /imls/load_d1_int/nto/mpiom07
mkdir -p /imls/load_d1_list
mkdir -p /imls/load_d1_list/atm
mkdir -p /imls/load_d1_list/atm/geosfpit
mkdir -p /imls/load_d1_list/atm/geosit
mkdir -p /imls/load_d1_list/atm/merra2
mkdir -p /imls/load_d1_list/lws
mkdir -p /imls/load_d1_list/lws/geosfpit
mkdir -p /imls/load_d1_list/lws/geosit
mkdir -p /imls/load_d1_list/lws/merra2
mkdir -p /imls/load_d1_list/nto
mkdir -p /imls/load_d1_list/nto/mpiom06
mkdir -p /imls/load_d1_list/nto/mpiom07
mkdir -p /imls/load_d1_spl
mkdir -p /imls/load_d1_spl/atm
mkdir -p /imls/load_d1_spl/atm/geosfpit
mkdir -p /imls/load_d1_spl/atm/geosit
mkdir -p /imls/load_d1_spl/atm/merra2
mkdir -p /imls/load_d1_spl/lws
mkdir -p /imls/load_d1_spl/lws/geosfpit
mkdir -p /imls/load_d1_spl/lws/geosit
mkdir -p /imls/load_d1_spl/lws/merra2
mkdir -p /imls/load_d1_spl/nto
mkdir -p /imls/load_d1_spl/nto/mpiom06
mkdir -p /imls/load_d1_spl/nto/mpiom07
mkdir -p /imls/load_export
mkdir -p /imls/load_export/atm
mkdir -p /imls/load_export/atm/geosfpit
mkdir -p /imls/load_export/atm/geosit
mkdir -p /imls/load_export/atm/merra2
mkdir -p /imls/load_export/lws
mkdir -p /imls/load_export/lws/geosfpit
mkdir -p /imls/load_export/lws/geosit
mkdir -p /imls/load_export/lws/merra2
mkdir -p /imls/load_export/nto
mkdir -p /imls/load_export/nto/mpiom06
mkdir -p /imls/load_export/nto/mpiom07
mkdir -p /imls/load_grid
mkdir -p /imls/load_grid/atm
mkdir -p /imls/load_grid/atm/geosfpit
mkdir -p /imls/load_grid/atm/geosit
mkdir -p /imls/load_grid/atm/merra2
mkdir -p /imls/load_grid/lws
mkdir -p /imls/load_grid/lws/geosfpit
mkdir -p /imls/load_grid/lws/geosit
mkdir -p /imls/load_grid/lws/merra2
mkdir -p /imls/load_grid/nto
mkdir -p /imls/load_grid/nto/mpiom06
mkdir -p /imls/load_grid/nto/mpiom07
mkdir -p /imls/load_har_grid
mkdir -p /imls/load_har_grid/atm
mkdir -p /imls/load_har_grid/atm/geosfpit
mkdir -p /imls/load_har_grid/atm/geosit
mkdir -p /imls/load_har_grid/atm/merra2
mkdir -p /imls/load_har_grid/lws
mkdir -p /imls/load_har_grid/lws/geosfpit
mkdir -p /imls/load_har_grid/lws/geosit
mkdir -p /imls/load_har_grid/lws/merra2
mkdir -p /imls/load_har_grid/nto
mkdir -p /imls/load_har_grid/nto/mpiom06
mkdir -p /imls/load_har_grid/nto/mpiom07
mkdir -p /imls/load_har_grid/nto/omct05
mkdir -p /imls/load_har_grid/toc
mkdir -p /imls/load_har_grid/toc/equil01
mkdir -p /imls/load_har_grid/toc/equil02
mkdir -p /imls/load_har_grid/toc/fes2012
mkdir -p /imls/load_har_grid/toc/fes2014b
mkdir -p /imls/load_har_grid/toc/got410c
mkdir -p /imls/load_har_grid/toc/got48
mkdir -p /imls/load_har_grid/toc/lpequil
mkdir -p /imls/load_har_list
mkdir -p /imls/load_har_list/atm
mkdir -p /imls/load_har_list/atm/geosfpit
mkdir -p /imls/load_har_list/atm/geosit
mkdir -p /imls/load_har_list/atm/merra2
mkdir -p /imls/load_har_list/lws
mkdir -p /imls/load_har_list/lws/geosfpit
mkdir -p /imls/load_har_list/lws/geosit
mkdir -p /imls/load_har_list/lws/merra2
mkdir -p /imls/load_har_list/nto
mkdir -p /imls/load_har_list/nto/mpiom06
mkdir -p /imls/load_har_list/nto/mpiom07
mkdir -p /imls/load_har_list/toc
mkdir -p /imls/load_har_list/toc/equil01
mkdir -p /imls/load_har_list/toc/equil02
mkdir -p /imls/load_har_list/toc/fes2012
mkdir -p /imls/load_har_list/toc/fes2014b
mkdir -p /imls/load_har_list/toc/got410c
mkdir -p /imls/load_har_list/toc/got48
mkdir -p /imls/load_har_list/toc/got48/got48
mkdir -p /imls/load_har_list/toc/lpequil
mkdir -p /imls/load_har_spl
mkdir -p /imls/load_har_spl/atm
mkdir -p /imls/load_har_spl/atm/geosfpit
mkdir -p /imls/load_har_spl/atm/geosit
mkdir -p /imls/load_har_spl/atm/merra2
mkdir -p /imls/load_har_spl/lws
mkdir -p /imls/load_har_spl/lws/geosfpit
mkdir -p /imls/load_har_spl/lws/geosit
mkdir -p /imls/load_har_spl/lws/merra2
mkdir -p /imls/load_har_spl/nto
mkdir -p /imls/load_har_spl/nto/mpiom06
mkdir -p /imls/load_har_spl/nto/mpiom07
mkdir -p /imls/load_har_spl/toc
mkdir -p /imls/load_har_spl/toc/equil01
mkdir -p /imls/load_har_spl/toc/equil02
mkdir -p /imls/load_har_spl/toc/fes2012
mkdir -p /imls/load_har_spl/toc/fes2012/fes2012
mkdir -p /imls/load_har_spl/toc/fes2014b
mkdir -p /imls/load_har_spl/toc/got410c
mkdir -p /imls/load_har_spl/toc/got48
mkdir -p /imls/load_har_spl/toc/got48/got48
mkdir -p /imls/load_har_spl/toc/lpequil
mkdir -p /imls/load_int
mkdir -p /imls/load_int/atm
mkdir -p /imls/load_int/atm/geosfpit
mkdir -p /imls/load_int/atm/geosit
mkdir -p /imls/load_int/atm/merra2
mkdir -p /imls/load_int/lws
mkdir -p /imls/load_int/lws/geosfpit
mkdir -p /imls/load_int/lws/geosit
mkdir -p /imls/load_int/lws/merra2
mkdir -p /imls/load_int/nto
mkdir -p /imls/load_int/nto/mpiom06
mkdir -p /imls/load_int/nto/mpiom07
mkdir -p /imls/load_list
mkdir -p /imls/load_list/atm
mkdir -p /imls/load_list/atm/geosfpit
mkdir -p /imls/load_list/atm/geosit
mkdir -p /imls/load_list/atm/merra2
mkdir -p /imls/load_list/lws
mkdir -p /imls/load_list/lws/geosfpit
mkdir -p /imls/load_list/lws/geosit
mkdir -p /imls/load_list/lws/merra2
mkdir -p /imls/load_list/nto
mkdir -p /imls/load_list/nto/mpiom06
mkdir -p /imls/load_list/nto/mpiom07
mkdir -p /imls/load_sandbox
mkdir -p /imls/load_sandbox/atm
mkdir -p /imls/load_sandbox/atm/geosfpit
mkdir -p /imls/load_sandbox/atm/geosit
mkdir -p /imls/load_sandbox/atm/merra2
mkdir -p /imls/load_sandbox/lws
mkdir -p /imls/load_sandbox/lws/geosfpit
mkdir -p /imls/load_sandbox/lws/geosit
mkdir -p /imls/load_sandbox/lws/merra2
mkdir -p /imls/load_sandbox/nto
mkdir -p /imls/load_sandbox/nto/mpiom06
mkdir -p /imls/load_sandbox/nto/mpiom07
mkdir -p /imls/load_spl
mkdir -p /imls/load_spl/atm
mkdir -p /imls/load_spl/atm/geosfpit
mkdir -p /imls/load_spl/atm/geosit
mkdir -p /imls/load_spl/atm/merra2
mkdir -p /imls/load_spl/lws
mkdir -p /imls/load_spl/lws/geosfpit
mkdir -p /imls/load_spl/lws/geosit
mkdir -p /imls/load_spl/lws/merra2
mkdir -p /imls/load_spl/nto
mkdir -p /imls/load_spl/nto/mpiom06
mkdir -p /imls/load_spl/nto/mpiom07
mkdir -p /imls/vgep
mkdir -p /imls/vgep/atm
mkdir -p /imls/vgep/atm/geosfpit
mkdir -p /imls/vgep/atm/geosit
mkdir -p /imls/vgep/atm/merra2
mkdir -p /imls/vgep/lws
mkdir -p /imls/vgep/lws/geosfpit
mkdir -p /imls/vgep/lws/geosit
mkdir -p /imls/vgep/lws/merra2
mkdir -p /imls/vgep/nto
mkdir -p /imls/vgep/nto/mpiom06
mkdir -p /imls/vgep/nto/mpiom07
mkdir -p /imls/vgep/toc
mkdir -p /imls/vgep/toc/got410c
mkdir -p /imls/aam/ser
mkdir -p /imls/aam/merra2
mkdir -p /imls/aam/geosfp
mkdir -p /imls/aam/geosit
mkdir -p /imls/aam/geosfpit
