#!/bin/csh -f
set from = ""
set to   = "sa:"
#
#rsync -av "${from}/imls/heb/merra2/"               "${to}/imls/heb/merra2/"
#rsync -av "${from}/imls/heb/geosit/"               "${to}/imls/heb/geosit/"
#rsync -av "${from}/imls/heb/geosfpit/2024/"         "${to}/imls/heb/geosfpit/2024/"
#rsync -av "${from}/imls/heb/geosfpit/2025/"         "${to}/imls/heb/geosfpit/2025/"
#rsync -av "${from}/imls/heb/geosfp/2024"           "${to}/imls/heb/geosfp/2024"
#rsync -av "${from}/imls/heb/geosfp/2025"           "${to}/imls/heb/geosfp/2025"
#rsync -av "${from}/imls/orig_data/fes2014b_extr/"  "${to}/imls/orig_data/fes2014b_extr/"
#rsync -av "${from}/imls/orig_data/mpiom06/"        "${to}/imls/orig_data/mpiom06/"
#rsync -av "${from}/imls/orig_data/mpiom07/"        "${to}/imls/orig_data/mpiom07/"
#rsync -av  "${from}/imls/geos_fcs/heb/2025/"        "${to}/imls/geos_fcs/heb/2025/"
rsync -av  "${from}/imls/aam/ser/"                  "${to}/imls/aam/ser/"
rsync -av  "${from}/imls/aam/merra2/"               "${to}/imls/aam/merra2/"
rsync -av  "${from}/imls/aam/geosfpit/"             "${to}/imls/aam/geosfpit/"
rsync -av  "${from}/imls/aam/geosfp/"               "${to}/imls/aam/geosfp/"
rsync -av  "${from}/imls/aam/geosit/"               "${to}/imls/aam/geosit/"
