      SUBROUTINE DEBUG_MEM ( FLAG )
      LOGICAL*4  FLAG
!
      INTEGER*4  MEMORY_DEBUG_FLAG, MEMORY_DEBUG__YES
      PARAMETER  ( MEMORY_DEBUG__YES = 1020304908 )
      COMMON     / MEMORY_DEBUG / MEMORY_DEBUG_FLAG
!
      IF ( FLAG ) THEN
           MEMORY_DEBUG_FLAG = MEMORY_DEBUG__YES
         ELSE
           MEMORY_DEBUG_FLAG = 0
      END IF
      RETURN
      END  !#!  DEBUG_MEM  #!#
