#######################################################################
#								      #
#	Make file for building petools                                #
#						     		      #
#  %%%  18-MAR-2004  makefile   v1.0  (c) L. Petrov  18-MAR-2004 %%%  #
#								      #
#######################################################################
.SUFFIXES:
.SUFFIXES:	.f	.c	.o	.opt_o	.a	.d
#
SHELL = /bin/csh -f -c 'umask 0002; eval "$2"'

DATE = `date '+%Y%m%d'`

