      SUBROUTINE CFPOS(RECORD)
      IMPLICIT NONE
!
! 1.  CFPOS PROGRAM SPECIFICATION
!
! 1.1
!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
!  LOW-LEVEL I/O UTILITY TO GET INTERNAL POSITION IN CONTROL FILE,
!  IT TAKES INTO ACCOUNT THE EFFECT OF CFUNRD
!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
!
! 1.2 REFERENCES:
!
! 2.  CFPOS INTERFACE
!
! 2.1 Parameter File
!
! 2.2 INPUT Variables: None
!
! 2.3 OUTPUT Variables:
!
      INTEGER*4 RECORD
!
! RECORD - Current record number in control file
!
! 2.4 COMMON BLOCKS USED
      INCLUDE 'batcm.i'
!
! 2.5 SUBROUTINE INTERFACE
!
!       CALLING SUBROUTINES: ctrlfl,arcset
!       CALLED SUBROUTINES: None
!
! 3.  LOCAL VARIABLES
!
! 4.  HISTORY
!   WHO   WHEN   WHAT
!
! CFPOS PROGRAM STRUCTURE
!
      RECORD=SAVREC
      IF(KGOT) RECORD=RECORD-1
!
      RETURN
      END
