import os, inspect
#  Sur_sked configuration
#
#  Generated by sur_sked configuration on 2026.08.18-13:53:42
#
sur_sked_prefix   = "/opt64"
ners_prefix       = "/opt64"
sur_sked_exp      = "/vlbi"
sur_sked_stp      = "/opt64/share/sur_sked/stp"
sur_sked_prc      = "/opt64/share/sur_sked/prc"
sur_sked_frq      = "/opt64/share/sur_sked/seq"
sur_sked_freq_def = "/opt64/share/sur_sked/frq/freq_def.txt"
#
import sys
if ( not ners_prefix+"/bin"        in sys.path ): sys.path.append(ners_prefix+"/bin")
if ( not sur_sked_prefix+"/bin"    in sys.path ): sys.path.append(sur_sked_prefix+"/bin")
if ( not sur_sked_prefix+"/script" in sys.path ): sys.path.append(sur_sked_prefix+"/script")
#
if ( "SUR_SKED_STP"      in os.environ ): sur_sked_stp      = os.environ["SUR_SKED_STP"]
if ( "SUR_SKED_PRC"      in os.environ ): sur_sked_prc      = os.environ["SUR_SKED_PRC"]
if ( "SUR_SKED_FRQ"      in os.environ ): sur_sked_frq      = os.environ["SUR_SKED_FRQ"]
if ( "SUR_SKED_FREQ_DEF" in os.environ ): sur_sked_freq_def = os.environ["SUR_SKED_FREQ_DEF"]
def HERE():
    line = "%s Line %s:" % ( os.path.basename( inspect.getframeinfo(inspect.currentframe().f_back).filename ), \
                             inspect.getframeinfo(inspect.currentframe().f_back).lineno )
