build:	
	@echo "Please use ./vsdc_install.py "

.PHONY: install
install:
	@echo "Please use ./vsdc_install.py "

.PHONY: clean
clean:
	purge ./

tar:
	purge ./
	@echo "Please use ./vsdc_gen_distro.py"
