#######################################################################
#								      #
#	Make file for building malo                                   #
#						     		      #
#  %%%  12-OCT-2012  Makefile   v1.0  (c) L. Petrov  12-OCT-2012 %%%  #
#								      #
#######################################################################
.SUFFIXES:
.SUFFIXES:	.f	.c	.o	.opt_o	.a	.d
#
SHELL = /bin/csh -f -c 'umask 0022; eval "$2"'

DATE = `date '+%Y%m%d'`

