      CHARACTER*(*) FUNCTION INTTODECIMALR(INT)
      IMPLICIT NONE
      INTEGER*2 INT
!
!  INTTODECIMALR: convert I*2 variable to ascii string right justified
!
      CHARACTER*6 STRING
      INTEGER*2 ILR
!
      WRITE(STRING,'(I6)') INT
      ILR=LEN(INTTODECIMALR)
      INTTODECIMALR(MAX(1,ILR-5):ILR)=STRING(MAX(1,7-ILR):6)
      IF(ILR.GT.6) INTTODECIMALR(1:ILR-6)=' '
!
      RETURN
      END
