!
! %%
!
      CHARACTER    ATP__ROOT*%ROOT_LEN%
      CHARACTER    ATP__PREFIX*%PREFIX_LEN%
      CHARACTER    ATP__VERSION*%VERSION_LEN%
      PARAMETER  ( ATP__ROOT      = "%ROOT_VAL%" )
      PARAMETER  ( ATP__PREFIX    = "%PREFIX_VAL%" )
      PARAMETER  ( ATP__VERSION   = "%VERSION_VAL%"  )
