      SUBROUTINE PETOOLS_VERS ( VERS_STR )
      CHARACTER  VERS_STR*(*)
      CHARACTER  PETOOLS__LABEL*30
      PETOOLS__LABEL = 'petools 20241115'
      VERS_STR = PETOOLS__LABEL
      RETURN
      END  SUBROUTINE PETOOLS_VERS
