      SUBROUTINE SPLIT_AND_CASEFOLD ( STRING_IN, TOKEN, STRING_OUT )
      IMPLICIT   NONE
      INTEGER*4  LENGTH, CFREAD
!
      CHARACTER STRING_IN*(*), STRING_OUT*(*), TOKEN*(*)
!
 910  CONTINUE
         CALL SPLITSTRING ( STRING_OUT, TOKEN, STRING_IN )
         IF ( TOKEN(1:1) .EQ. '\' ) THEN
              LENGTH = CFREAD ( STRING_IN )
              GOTO 910
         END IF
      CONTINUE
      CALL CASEFOLD ( TOKEN )
      RETURN
      END  !#!  SPLIT_AND_CASEFOLD  #!#
